2021-06-18 21:00:38.644947: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cosma/local/intel/Parallel_Studio_XE_2020/compilers_and_libraries_2020.2.254/linux/mpi/intel64/libfabric/lib:/cosma/local/intel/Parallel_Studio_XE_2020/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib/release:/cosma/local/intel/Parallel_Studio_XE_2020/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib:/cosma/local/ucx/1.8.1/lib:/cosma/local/intel/Parallel_Studio_XE_2020/compilers_and_libraries_2020.2.254/linux/compiler/lib/intel64_lin
2021-06-18 21:00:38.645516: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cosma/local/intel/Parallel_Studio_XE_2020/compilers_and_libraries_2020.2.254/linux/mpi/intel64/libfabric/lib:/cosma/local/intel/Parallel_Studio_XE_2020/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib/release:/cosma/local/intel/Parallel_Studio_XE_2020/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib:/cosma/local/ucx/1.8.1/lib:/cosma/local/intel/Parallel_Studio_XE_2020/compilers_and_libraries_2020.2.254/linux/compiler/lib/intel64_lin
2021-06-18 21:00:38.645553: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2021-06-18 21:00:44.378522: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cosma/local/intel/Parallel_Studio_XE_2020/compilers_and_libraries_2020.2.254/linux/mpi/intel64/libfabric/lib:/cosma/local/intel/Parallel_Studio_XE_2020/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib/release:/cosma/local/intel/Parallel_Studio_XE_2020/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib:/cosma/local/ucx/1.8.1/lib:/cosma/local/intel/Parallel_Studio_XE_2020/compilers_and_libraries_2020.2.254/linux/compiler/lib/intel64_lin
2021-06-18 21:00:44.378776: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2021-06-18 21:00:44.378817: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (m6010.pri.cosma7.alces.network): /proc/driver/nvidia/version does not exist
2021-06-18 21:00:44.395233: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2600090000 Hz
2021-06-18 21:00:44.397977: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55dd25e40d90 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-06-18 21:00:44.398004: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Using TensorFlow backend.
/cosma/home/dp004/dc-bian1/.local/lib/python3.7/site-packages/py21cmfast/_cfg.py:50: UserWarning: Your configuration file is out of date. Updating...
  "Your configuration file is out of date. Updating..."
/cosma/home/dp004/dc-bian1/.local/lib/python3.7/site-packages/py21cmfast/_cfg.py:33: UserWarning: Your configuration file is out of date. Updating...
  warnings.warn("Your configuration file is out of date. Updating...")
  0%|          | 0/552 [00:00<?, ?it/s]100%|██████████| 552/552 [00:00<00:00, 7979.90it/s]QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/21583', please create it with 0700 permissions.
qt.qpa.screen: QXcbConnection: Could not connect to display localhost:16.0
Could not connect to any X display.

